### ISSUE TITLE
User can filter books by genre

### ISSUE THREAD

**Issue by cgmccanna** [cgmccanna/ajax-project-1222#1]
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users will be able to choose a genre of book from a dropdown list, and will then be shown a list of books that belong to their chosen genre from the OpenLibrary API
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a basic HTML skeleton
- [x] Set the background to chosen image
- [x] Create an empty Nav bar that fits at the top of the page
- [x] To the navbar, add 4 links called "Genres", "Random", "My Collection", and "Search"
- [x] Create center title for the homepage
- [x] Create 3 buttons centered on the home page called "Browse By Genre", "Surprise Me", and "My Collection"
- [x] Create a new div with the data-view of 'genres'
- [x] Define a function called switchView which switches the data models data-view depending on the event target
- [x] listen for clicks on the document and set the data view to the class of the event target, and call the switchView function
- [x] Develop the Genres page using HTML and CSS to match figma wireframes
- [x] create dummy book elements using css and html, to match wireframes
- [x] Create a 'ul' element with an id of 'book-list' to hold the list of books
- [x] create a function called 'renderBook' which will...
     - [x]  create an empty book card element
     - [x] pull text content from 
     - [x] append the book card to the page
- [x] listen for change events on each of the select element and...
     - [x] Create a new XMLHttpRequest() object
     - [x] open() the xhr object and send a 'GET' request to 'http://openlibrary.org/subjects/' + '(event.target.className)' + '.json'
     - [x] Set the responseType to json
     - [x] Listen for the 'load' event on the xhr object in order to:
          - [x] loop through the response of the xhr object.
          - [x] for each book object in the response, call the renderBook function and append the return to the '#book-list' element
- [ ] Ensure that page looks good on mobile screen as well as desktop
- [ ] Remove all console logs, commented out code, and CSS properties that have no effect.
